# Generated by Django 5.0.1 on 2024-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='character',
            field=models.CharField(default='Unknown', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='Unknown', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='story',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.IntegerField(),
        ),
    ]
