# Generated by Django 5.0.1 on 2024-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('content', models.CharField(max_length=1000, verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=1, verbose_name='아이디어 관심도')),
                ('devtool', models.CharField(max_length=24, verbose_name='예상 개발 툴')),
            ],
        ),
    ]
