# Generated by Django 5.0.1 on 2024-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_idea_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.CharField(max_length=24, verbose_name='예상 개발 툴'),
        ),
    ]
